CREATE TABLE IF NOT EXISTS tasks (
    id INT AUTO_INCREMENT PRIMARY KEY,
    gtitle VARCHAR(255) NOT NULL,
    description TEXT,
    priority INT NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE
    );